apiVersion: apps/v1
kind: Deployment
metadata:
  name: certsvice-api
spec:
  selector:
    matchLabels:
      app: certsvice-api
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: certsvice-api
    spec:
      containers:
        - name: certsvice-api
