apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: certsvice-api
  name: certsvice-api
spec:
  ports:
    - name: 8080-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: certsvice-api
  type: NodePort
status:
  loadBalancer: {}
