name: Backoffice - Development

on:
  workflow_dispatch:
  push:
    paths:
      - "back-office/**"
      - ".github/workflows/dev-back-office.yaml"
    branches:
      - develop
jobs:
  deploy:
    name: deploy
    defaults:
      run:
        working-directory: ./back-office
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm install
      - name: Create .env file
        run: |
          echo "NEXT_PUBLIC_CONTRACT=${{ secrets.REACT_APP_CONTRACT_ADDRESS }}" >> .env &&
          echo "NEXT_PUBLIC_API_URI=${{ secrets.API_URI }}" >> .env
      - name: Build
        run: npm run build && npm run export
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      - name: Deploy
        run: aws s3 sync out/ s3://${{ secrets.AWS_S3_BUCKET_BACK_OFFICE }} --cache-control max-age=600
